-- Build 27.1: Studio Suite — generated graphics (Lineup, Match Day, Final Score)
-- Purpose: persist every PNG generated by <LineupStudio />, <MatchDayStudio />,
-- and <FinalScoreStudio /> so the team can re-publish, audit, and the AI Caption
-- Engine (Phase 2.4, Nebius Llama 3.3-70B) can stack captions against the saved
-- graphic, and One-Tap Publish (Phase 2.5, Buffer + Zapier) can record results.
--
-- Doctrine: routing not inventory. This is the audit row for graphics that
-- compose existing athlete identity records — no duplication of athlete data.
--
-- Safety:
-- - CREATE TYPE wrapped in DO/EXCEPTION so a re-run is idempotent.
-- - CREATE TABLE uses IF NOT EXISTS.
-- - Indexes use IF NOT EXISTS.

DO $$ BEGIN
  CREATE TYPE "studio_graphic_type" AS ENUM ('lineup','matchday','finalscore');
EXCEPTION WHEN duplicate_object THEN null; END $$;

CREATE TABLE IF NOT EXISTS "studio_graphics" (
  "id"           serial PRIMARY KEY,
  "userId"       integer NOT NULL,
  "type"         "studio_graphic_type" NOT NULL,
  "teamName"     varchar(160) NOT NULL,
  "opponent"     varchar(160),
  "gameDate"     varchar(10),
  "pngUrl"       text,
  "payload"      json,
  "captions"     json,
  "publishedTo"  json,
  "createdAt"    timestamp NOT NULL DEFAULT now(),
  "updatedAt"    timestamp NOT NULL DEFAULT now()
);

-- Lookup by owner (most common UI query: list a user's graphics newest first).
CREATE INDEX IF NOT EXISTS "studio_graphics_user_created_idx"
  ON "studio_graphics" ("userId", "createdAt" DESC);

-- Lookup by type within a user (tab switcher filtered views).
CREATE INDEX IF NOT EXISTS "studio_graphics_user_type_idx"
  ON "studio_graphics" ("userId", "type");

-- Lookup by gameDate (calendar correlations + matchday/finalscore lifecycle joins).
CREATE INDEX IF NOT EXISTS "studio_graphics_game_date_idx"
  ON "studio_graphics" ("gameDate")
  WHERE "gameDate" IS NOT NULL;
