/**
 * AthlynX — Social Command Center
 * Private AI post generation plus approved social publishing workflows
 * Avatar sync — all in one page
 */
import PlatformLayout from "@/components/PlatformLayout";
import MobileBottomNav from '@/components/MobileBottomNav'
import { useState } from "react";
import { RouteErrorBoundary } from "@/components/GlobalErrorBoundary";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { Link } from "wouter";
import { toast } from "sonner";

const PLATFORMS = [
  { id: "linkedin", label: "LinkedIn", emoji: "💼", color: "bg-blue-700", desc: "Professional, investor-facing" },
  { id: "instagram", label: "Instagram", emoji: "📸", color: "bg-gradient-to-r from-pink-600 to-purple-600", desc: "Visual, casual, hashtags" },
  { id: "twitter", label: "X / Twitter", emoji: "🐦", color: "bg-slate-800", desc: "Punchy, under 280 chars" },
  { id: "facebook", label: "Facebook", emoji: "👥", color: "bg-blue-600", desc: "Community, conversational" },
  { id: "tiktok", label: "TikTok", emoji: "🎵", color: "bg-black", desc: "Gen-Z energy, hooks" },
  { id: "all", label: "All Platforms", emoji: "🌐", color: "bg-gradient-to-r from-cyan-600 to-blue-600", desc: "Generate for all at once" },
];

const TONES = [
  { id: "professional", label: "Professional", emoji: "👔" },
  { id: "casual", label: "Casual", emoji: "😎" },
  { id: "hype", label: "Hype", emoji: "🔥" },
  { id: "inspirational", label: "Inspirational", emoji: "⭐" },
  { id: "educational", label: "Educational", emoji: "📚" },
];

const POST_TEMPLATES = [
  "AthlynX is live — Pre-Seed round open, $1.5M at $15M valuation",
  "Introducing the #1 AI platform for athletes — athlynx.ai",
  "NIL market is $2.5B and untapped. We built the solution.",
  "Built for less than $145K. A traditional team would charge $2M.",
  "520,000+ NCAA athletes. Nobody serves them end-to-end. Until now.",
  "Iron Sharpens Iron — Proverbs 27:17",
];

function SocialCommandCenterInner() {
  const { user } = useAuth();
  const [topic, setTopic] = useState("");
  const [tone, setTone] = useState<"professional" | "casual" | "hype" | "inspirational" | "educational">("professional");
  const [selectedPlatform, setSelectedPlatform] = useState("linkedin");
  const [generatedPosts, setGeneratedPosts] = useState<Record<string, string>>({});
  const [editedPost, setEditedPost] = useState("");
  const [activeGenPlatform, setActiveGenPlatform] = useState("linkedin");
  const [publishChannels, setPublishChannels] = useState<string[]>(["twitter", "instagram"]);
  const [publishLog, setPublishLog] = useState<{ platform: string; status: string; time: string }[]>([]);

  const generateMutation = trpc.social.generatePost.useMutation({
    onSuccess: (data) => {
      setGeneratedPosts(data.posts);
      const firstPlatform = Object.keys(data.posts)[0];
      setActiveGenPlatform(firstPlatform);
      setEditedPost(data.posts[firstPlatform] || "");
      toast.success("✨ Posts generated by Gemini AI!");
    },
    onError: (e) => toast.error(e.message || "Generation failed"),
  });

  const bufferMutation = trpc.social.publishToBuffer.useMutation({
    onSuccess: (data) => {
      const successChannels = data.results?.filter((r: any) => r.success).map((r: any) => r.channel).join(", ");
      toast.success(`✅ Posted to ${successChannels || data.posted + " channel(s)"}!`);
      setPublishLog(p => [...p, { platform: `Buffer: ${successChannels}`, status: "✅ Published", time: new Date().toLocaleTimeString() }]);
    },
    onError: (e) => toast.error(e.message || "Buffer post failed"),
  });

  const linkedinMutation = trpc.social.publishToLinkedIn.useMutation({
    onSuccess: () => {
      toast.success("✅ Posted to LinkedIn!");
      setPublishLog(p => [...p, { platform: "LinkedIn", status: "✅ Published", time: new Date().toLocaleTimeString() }]);
    },
    onError: (e) => toast.error(e.message || "LinkedIn post failed"),
  });

  const publishAllMutation = trpc.social.publishToAll.useMutation({
    onSuccess: (data) => {
      toast.success(`✅ Published to ${data.totalPosted} platform(s)!`);
      setPublishLog(p => [...p, { platform: "All Platforms", status: `✅ ${data.totalPosted} published`, time: new Date().toLocaleTimeString() }]);
    },
    onError: (e) => toast.error(e.message),
  });

  const avatarMutation = trpc.social.syncGravatar.useMutation({
    onSuccess: (data) => {
      if (data.synced) toast.success("✅ Avatar synced! Hard refresh to see your photo.");
      else toast.info(data.message);
    },
    onError: (e) => toast.error(e.message),
  });

  const handleGenerate = () => {
    if (!topic.trim()) { toast.error("Enter a topic first"); return; }
    generateMutation.mutate({ topic, platform: selectedPlatform as any, tone });
  };

  const handlePublishLinkedIn = () => {
    if (!editedPost.trim()) { toast.error("Generate a post first"); return; }
    toast.info("Direct posting is disabled. Route this through Media OS for vault, Lee review, Chad approval, connector proof, and audit trail.");
    setPublishLog(p => [...p, { platform: "LinkedIn", status: "Held for Media OS approval", time: new Date().toLocaleTimeString() }]);
  };

  const handlePublishBuffer = () => {
    if (!editedPost.trim()) { toast.error("Generate a post first"); return; }
    const channels = publishChannels.filter(c => ["twitter", "facebook", "instagram", "tiktok"].includes(c));
    if (!channels.length) { toast.error("Select at least one channel"); return; }
    toast.info("Buffer/Zapier are fallback rails only. Save this to Media OS before any external action.");
    setPublishLog(p => [...p, { platform: `Buffer fallback: ${channels.join(", ")}`, status: "Connector-gated", time: new Date().toLocaleTimeString() }]);
  };

  const handlePublishAll = () => {
    if (!editedPost.trim()) { toast.error("Generate a post first"); return; }
    toast.info("Publish Everywhere is now queue-first. Use Media OS for vault, quality gates, approval, connector check, and proof.");
    setPublishLog(p => [...p, { platform: "All Platforms", status: "Queued path required", time: new Date().toLocaleTimeString() }]);
  };

  const isPublishing = bufferMutation.isPending || linkedinMutation.isPending || publishAllMutation.isPending;

  return (
    <PlatformLayout>
      <div className="space-y-6 pb-20 lg:pb-4 max-w-4xl mx-auto">
        {/* Header */}
        <div className="bg-gradient-to-r from-blue-900 via-indigo-900 to-blue-900 border border-blue-800 rounded-2xl p-6">
          <div className="flex items-center gap-4 mb-2">
            <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-cyan-500 to-blue-600 flex items-center justify-center text-2xl shadow-lg">📱</div>
            <div>
              <h1 className="text-2xl font-black text-white">Social Command Center</h1>
              <p className="text-cyan-400 text-sm">AI content, social publishing, and identity tools — all in one place</p>
            </div>
          </div>
          {user && (
            <div className="flex items-center gap-3 mt-4 p-3 bg-blue-950/50 rounded-xl border border-blue-800">
              <div className="w-10 h-10 rounded-full overflow-hidden border-2 border-cyan-500">
                {user.avatarUrl ? (
                  <img src={user.avatarUrl} alt={user.name || ""} className="w-full h-full object-cover" />
                ) : (
                  <div className="w-full h-full bg-blue-700 flex items-center justify-center text-white font-black">
                    {(user.name || "A").charAt(0)}
                  </div>
                )}
              </div>
              <div className="flex-1">
                <div className="text-white font-bold text-sm">{user.name}</div>
                <div className="text-blue-400 text-xs">{user.email}</div>
              </div>
              <button
                onClick={() => avatarMutation.mutate()}
                disabled={avatarMutation.isPending}
                className="bg-blue-700 hover:bg-blue-600 text-white text-xs font-bold px-3 py-1.5 rounded-lg transition-colors disabled:opacity-50"
              >
                {avatarMutation.isPending ? "Syncing..." : "Sync Avatar"}
              </button>
            </div>
          )}
        </div>

        {/* OS Doctrine */}
        <div className="bg-[#0d1f3c] border border-cyan-500/30 rounded-2xl p-5">
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
            <div>
              <h2 className="text-white font-black text-lg">AthlynXAI Media OS is the brain</h2>
              <p className="text-blue-300 text-sm mt-1">Generate here, then move final assets through Media OS: vault, Lee review, Chad approval, connector checkpoint, distribution proof, and watchdog.</p>
            </div>
            <Link href="/media-os">
              <span className="inline-flex bg-cyan-500 hover:bg-cyan-400 text-[#061426] font-black px-4 py-3 rounded-xl cursor-pointer">Open Media OS</span>
            </Link>
          </div>
        </div>

        {/* Post Generator */}
        <div className="bg-[#1a3a8f] border border-blue-900 rounded-2xl p-5 space-y-5">
          <h2 className="text-white font-black text-lg flex items-center gap-2">✨ Gemini AI Post Generator</h2>

          {/* Platform selector */}
          <div>
            <label className="text-blue-400 text-xs font-bold mb-2 block uppercase tracking-wide">Target Platform</label>
            <div className="grid grid-cols-3 sm:grid-cols-6 gap-2">
              {PLATFORMS.map(p => (
                <button key={p.id} onClick={() => setSelectedPlatform(p.id)}
                  className={`flex flex-col items-center p-2.5 rounded-xl text-xs font-bold transition-all border ${
                    selectedPlatform === p.id
                      ? "border-cyan-500 bg-cyan-500/20 text-white scale-105"
                      : "border-blue-800 bg-blue-900/30 text-blue-400 hover:border-blue-600"
                  }`}>
                  <span className="text-xl mb-1">{p.emoji}</span>
                  <span className="leading-tight text-center">{p.label}</span>
                </button>
              ))}
            </div>
          </div>

          {/* Tone selector */}
          <div>
            <label className="text-blue-400 text-xs font-bold mb-2 block uppercase tracking-wide">Tone</label>
            <div className="flex flex-wrap gap-2">
              {TONES.map(t => (
                <button key={t.id} onClick={() => setTone(t.id as any)}
                  className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${
                    tone === t.id ? "bg-blue-600 text-white" : "bg-blue-900/50 text-blue-400 hover:bg-blue-800"
                  }`}>
                  {t.emoji} {t.label}
                </button>
              ))}
            </div>
          </div>

          {/* Topic input */}
          <div>
            <label className="text-blue-400 text-xs font-bold mb-2 block uppercase tracking-wide">Topic / What to post about</label>
            <textarea
              value={topic}
              onChange={e => setTopic(e.target.value)}
              placeholder="e.g. AthlynX is live — Pre-Seed round open at $15M valuation..."
              rows={2}
              className="w-full bg-[#0d1f3c] border border-blue-800 text-white text-sm rounded-xl px-4 py-3 focus:outline-none focus:border-cyan-500 placeholder-blue-600 resize-none"
            />
            {/* Quick templates */}
            <div className="flex flex-wrap gap-1.5 mt-2">
              {POST_TEMPLATES.map((t, i) => (
                <button key={i} onClick={() => setTopic(t)}
                  className="text-xs bg-blue-900/60 hover:bg-blue-800 text-blue-400 px-2.5 py-1 rounded-lg transition-colors border border-blue-800/50">
                  {t.length > 40 ? t.slice(0, 40) + "..." : t}
                </button>
              ))}
            </div>
          </div>

          <button
            onClick={handleGenerate}
            disabled={generateMutation.isPending || !topic.trim()}
            className="w-full bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 text-white font-black py-4 rounded-xl transition-all disabled:opacity-50 text-base flex items-center justify-center gap-2 shadow-lg shadow-cyan-900/30"
          >
            {generateMutation.isPending ? (
              <><span className="animate-spin inline-block">⚡</span> Gemini is writing your post...</>
            ) : (
              <><span>✨</span> Generate with Gemini AI</>
            )}
          </button>
        </div>

        {/* Generated Posts Editor */}
        {Object.keys(generatedPosts).length > 0 && (
          <div className="bg-[#1a3a8f] border border-blue-900 rounded-2xl p-5 space-y-4">
            <h2 className="text-white font-black text-lg flex items-center gap-2">📝 Edit & Publish</h2>

            {/* Platform tabs */}
            {Object.keys(generatedPosts).length > 1 && (
              <div className="flex flex-wrap gap-2">
                {Object.keys(generatedPosts).map(p => (
                  <button key={p} onClick={() => { setActiveGenPlatform(p); setEditedPost(generatedPosts[p]); }}
                    className={`text-xs px-3 py-1.5 rounded-lg font-bold transition-colors ${activeGenPlatform === p ? "bg-blue-600 text-white" : "bg-blue-900 text-blue-400 hover:bg-blue-800"}`}>
                    {p.charAt(0).toUpperCase() + p.slice(1)}
                  </button>
                ))}
              </div>
            )}

            <textarea
              value={editedPost}
              onChange={e => setEditedPost(e.target.value)}
              rows={8}
              className="w-full bg-[#0d1f3c] border border-blue-800 text-white text-sm rounded-xl px-4 py-3 focus:outline-none focus:border-cyan-500 resize-none"
            />
            <div className="text-blue-500 text-xs">{editedPost.length} characters</div>

            {/* Publish buttons */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
              {/* LinkedIn */}
              <button onClick={handlePublishLinkedIn} disabled={isPublishing}
                className="flex items-center justify-center gap-2 bg-blue-700 hover:bg-blue-600 text-white font-bold py-3 rounded-xl transition-all disabled:opacity-50">
                Hold for LinkedIn Approval
              </button>

              {/* Buffer */}
              <div className="space-y-2">
                <div className="flex flex-wrap gap-1.5">
                  {["twitter", "instagram", "facebook", "tiktok"].map(ch => (
                    <button key={ch} onClick={() => setPublishChannels(p => p.includes(ch) ? p.filter(c => c !== ch) : [...p, ch])}
                      className={`text-xs px-2 py-1 rounded-lg font-bold transition-all ${publishChannels.includes(ch) ? "bg-blue-600 text-white" : "bg-blue-900 text-blue-400"}`}>
                      {ch === "twitter" ? "X" : ch.charAt(0).toUpperCase() + ch.slice(1)}
                    </button>
                  ))}
                </div>
                <button onClick={handlePublishBuffer} disabled={isPublishing}
                  className="w-full flex items-center justify-center gap-2 bg-orange-600 hover:bg-orange-500 text-white font-bold py-3 rounded-xl transition-all disabled:opacity-50">
                  Hold for Buffer Fallback
                </button>
              </div>

              {/* Publish All */}
              <button onClick={handlePublishAll} disabled={isPublishing}
                className="flex items-center justify-center gap-2 bg-gradient-to-r from-green-600 to-emerald-600 hover:from-green-500 hover:to-emerald-500 text-white font-bold py-3 rounded-xl transition-all disabled:opacity-50">
                Route Through Media OS
              </button>
            </div>
          </div>
        )}

        {/* Publish Log */}
        {publishLog.length > 0 && (
          <div className="bg-[#1a3a8f] border border-blue-900 rounded-2xl p-4">
            <h3 className="text-white font-bold mb-3">Queue / Hold History</h3>
            <div className="space-y-2">
              {publishLog.slice().reverse().map((log, i) => (
                <div key={i} className="flex items-center justify-between bg-[#1530a0] rounded-xl px-3 py-2">
                  <div className="text-white text-sm font-bold">{log.platform}</div>
                  <div className="flex items-center gap-3">
                    <span className="text-green-400 text-xs font-bold">{log.status}</span>
                    <span className="text-blue-500 text-xs">{log.time}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Quick links */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          {[
            { label: "AI Content", href: "/ai-content", emoji: "✨", color: "from-fuchsia-600 to-pink-600" },
            { label: "X-Factor Feed", href: "/x-factor", emoji: "⚡", color: "from-yellow-600 to-orange-600" },
            { label: "Social Hub", href: "/social-hub", emoji: "🌐", color: "from-teal-600 to-cyan-600" },
            { label: "My Profile", href: "/profile", emoji: "👤", color: "from-blue-600 to-indigo-600" },
          ].map(l => (
            <Link key={l.href} href={l.href}>
              <div className={`flex items-center gap-2 bg-gradient-to-r ${l.color} text-white text-sm font-bold px-4 py-3 rounded-xl transition-all hover:scale-105 cursor-pointer shadow-lg`}>
                <span className="text-lg">{l.emoji}</span>{l.label}
              </div>
            </Link>
          ))}
        </div>
      <MobileBottomNav />
    </div>
    </PlatformLayout>
  );
}

export default function SocialCommandCenter() {
  return <RouteErrorBoundary><SocialCommandCenterInner /></RouteErrorBoundary>;
}
